package.json
Fix https://github.com/charliermarsh/ruff-vscode to https://github.com/charliermarsh/vscode-ruff.
=> Fix incorrect repository URL

CHANGELOG.md
When getting an extension update it's nice to take a quick look at new features and changes that come with it.
This PR adds a CHANGELOG.md which should be picked up by the vscode extension to display a changelog tab.
I've added the most recent releases and ideally, this would also include all changes from ruff between the different versions of the vscode extension. 
However, lowest maintenance effort is probably to simply copy the auto-generated vscode-ruff release notes into the CHANGELOG.md or to just point a link to the github release notes (see example below), which is not nice but at least users can access the release notes with a click.
=> add changelog.md

bundled/tool/jsonrpc.py
This cleans up Ruff's "Output" tab in VSCode and fixes #53
=> Fix 'Exception ignored in atexit callback' in jsonrpc

README.md
=> Clarify Black + Ruff compatibility in README

bundled/tool/server.py
We have some colleagues using vscode and got an error message `AttributeError: module 'ruff_lsp.server' has no attribute 'set_bundle'`, this pr gives a mo clearer error message.
When you execute `❯ .venv\Scripts\python.exe bundled\tool\server.py` with ruff-lsp v0.0.5 you get
```
Traceback (most recent call last):
File "src\ruff-vscode\bundled\tool\server.py", line 29, in <module>
server.set_bundle(os.fspath(BUNDLE_DIR / "libs" / "bin" / server.TOOL_MODULE))
AttributeError: module 'ruff_lsp.server' has no attribute 'set_bundle'
```
Now you get
```
Traceback (most recent call last):
File "src\ruff-vscode\bundled\tool\server.py", line 27, in <module>
raise RuntimeError("ruff-vscode needs at least ruff-lsp v0.0.6")
RuntimeError: ruff-vscode needs at least ruff-lsp v0.0.6
```
=> Confusing error message if old ruff-lsp package installed

package.json
Add the `*.trace.server` setting to the configuration option, so that configuration completion also works in `settings.json`.
**VSCode Reference**:
- <https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#logging-support-for-language-server>
**Examples of other extensions**:
- <https://github.com/redhat-developer/vscode-yaml/blob/main/package.json#L104-L113>
- and more...
https://user-images.githubusercontent.com/188642/213360027-b48bcb32-3b49-4f5c-8301-135b3571e23d.mp4
=> Expose the ruff.trace.server setting for tracing ruff-lsp activity

.github/workflows/release.yaml
This only fixes the Linux issues, aarch64 Windows has the same kind of issue, macOS is fine thanks to universal2 binary.
Closes #58 
Closes #117
=> Install the right version of ruff in aarch64 & armhf Linux targets

package-lock.json, package.json, src/common/python.ts
The Python Environment API currently used by the extension has been deprecated.
[The base template also uses the new API.](https://github.com/microsoft/vscode-python-tools-extension-template/commit/620e863b5f6de9db092be3438c806154a7d5ae5a)
=> Use new Python Environment API

src/extension.ts
This hopefully solves #127
I still have to find a better way to test this
=> Only one server restart at a time

package.json, src/common/server.ts, src/extension.ts
In #194, we stopped setting the `client` returned by the `clientPromise`. As a result, the "Fix all" action stopped working, since it relies on the `client`.
Closes #194.
=> Restore client in `extension.ts`

CHANGELOG.md, package.json
Simple fix to the new canonical URL of the `ruff-vscode` project.
I clicked them all! 😁
=> Fix links to canonical repository URL

bundled/tool/server.py
I guess it's, like, _possible_ that some users already have the bundled library in their `sys.path`? There's no harm in adding it again, we want it to be at the front.
=> Always add bundled directory to front of path

package.json, src/common/server.ts, src/common/settings.ts
This PR adds an `enableExperimentalFormatter` flag to the extension which turns on formatting capabilities by setting the environment variable in the LSP server. Our extension is setup such that if you change this setting, we restart the server, so it is respected across modifications. This is (intentionally) more discoverable, as I had trouble with the environment variable alone.
- Run the extension locally.
- Set `"editor.defaultFormatter": "charliermarsh.ruff"` in `settings.json`.
- Try to format; verify that Ruff is not a valid option.
- Enable the setting (`"ruff.enableExperimentalFormatter": true`).
- Try to format; verify that it works as expected.
- Disable the setting; try to format; verify that it fails as expected:
=> Add a VS Code setting to enable the experimental formatter

README.md
My original goal was just to update the deprecated setting python.formatting.provider (per https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions) but then I also updated a bunch of charliemarsh urls to astral-sh.
Click links, see result in window.
For setting change, I checked with VS code team and will also test in profile/devcontainer.
=> Update README.md with black and URLs

package.json
fixes #289 
verified that the setting now shows in the workspace tab:
=> allow `enableExperimentalFormatter` to be configured in the workspace

package.json, src/common/settings.ts
This is the peer PR to https://github.com/astral-sh/ruff-lsp/pull/255, adding `ruff.lint.args` and `ruff.lint.run` to the VS Code settings. Again, these changes are backwards-compatible, and the deprecations are also visible in the VS Code UI. (Specifically, according to the [VS Code documentation](https://code.visualstudio.com/api/references/contribution-points), these settings _won't_ show up in the VS Code UI.)
=> Move args and run settings to `lint.args` and `lint.run`

package.json, pyproject.toml, requirements-dev.txt, requirements.txt, src/common/settings.ts, src/extension.ts
This is the peer PR to https://github.com/astral-sh/ruff-lsp/pull/255, which adds `lint.args` and `lint.run` to the VS Code extension, and deprecates `args` and `run`:
The behavior is as follows:
- If you have `lint.run` defined in your settings, we will respect it and ignore `run`.
- Otherwise, if you have `run` defined in your settings, we will respect it.
- Otherwise, we fall back to the default value.
Confusingly, if you set `run`, VS Code _still_ doesn't show it in the visual settings UI, which is unfortunate, as one edge case here is:
- You have `run` defined.
- You set `lint.run` in the visual UI.
- (`run` is still defined in your `settings.json`, but not visible in the UI.)
- You unset `lint.run` in the visual UI.
- (VS Code then removes `lint.run` from your `settings.json`, since …
=> Move `args` and `run` settings to `lint.args` and `lint.run`

package.json, src/common/settings.ts
This is a peer PR to https://github.com/astral-sh/ruff-lsp/pull/258, adding `format.args` to the VS Code extension.
=> Add a `format.args` setting to the VS Code extension

CHANGELOG.md, package-lock.json, package.json, pyproject.toml
Closes https://github.com/astral-sh/ruff-vscode/issues/303
=> Bump extension version to 2023.42.0

README.md
These changes assume that the `enableExperimentalFormatter` setting has been removed.
=> Add formatter to README

src/common/server.ts, src/common/status.ts, src/common/utilities.ts, src/common/vscodeapi.ts, src/extension.ts
Closes https://github.com/astral-sh/ruff-vscode/issues/343.
Ran the VS Code extension; verified that the "Ruff: Open logs" command showed up in the Python language status menu.
=> Add register-status hooks to extension

.github/workflows/release.yaml
At some point between 2023.50.0 and 2023.52.0, something changed in the GitHub Actions runners such that both the x86 and ARM mac builds starting using Ruff's x86 wheel. This breaks the extension when using the bundled Ruff on an M-series MacBook. (In 2023.50.0 and earlier, it turns out we were using the universal wheel for the x86 build too, which is okay, though not identical to what pip does on x86 machines.)
This PR forces the build pipeline to use the M-series MacBooks for macOS builds, and then sets the arch explicitly. As such, we now use universal for the ARM extension and x86 for the x86 extension.
=> Build ARM Mac extension on M1 runners

.vscodeignore
Excludes `scripts/` (added in [#251](https://github.com/astral-sh/ruff-vscode/pull/251)) from the extension bundle as it is not required.
Current bundle:
```console
extension/
├─ bundled/
├─ dist/
├─ scripts/
│  ├─ bump_extension_version.sh
│  ├─ bump_lsp_version.sh
│  ├─ bump_ruff_version.sh
├─ CHANGELOG.md
├─ icon.png
├─ LICENSE.txt
├─ package.json
├─ pyproject.toml
├─ README.md
```
Built the package, installed it manually through ruff.vsix and launched the extension to verify continued functionality.
```console
python -m pip install -t ./bundled/libs --implementation py --no-deps --upgrade -r ./requirements.txt
npm install
npm run vsce-package
```
=> Exclude scripts directory from extension bundle

README.md
Current ruff versions in README badges use `0.1.0`...
[![image](https://img.shields.io/pypi/v/ruff/0.1.0.svg)](https://pypi.python.org/pypi/ruff)
[![image](https://img.shields.io/pypi/l/ruff/0.1.0.svg)](https://pypi.python.org/pypi/ruff)
[![image](https://img.shields.io/pypi/pyversions/ruff/0.1.0.svg)](https://pypi.python.org/pypi/ruff)
...instead of `0.1.9`:
[![image](https://img.shields.io/pypi/v/ruff/0.1.9.svg)](https://pypi.python.org/pypi/ruff)
[![image](https://img.shields.io/pypi/l/ruff/0.1.9.svg)](https://pypi.python.org/pypi/ruff)
[![image](https://img.shields.io/pypi/pyversions/ruff/0.1.9.svg)](https://pypi.python.org/pypi/ruff)
Looks like missed in bump from `0.1.0` to `0.1.2` (#309).
Updated the badges to `0.1.9` and then executed the script to bump the versions.
```console …
```
=> Update ruff README badge versions to 0.1.9

README.md
Looks like this line got prefixed with `notebook` despite the setting targeting non-notebook files. Just a one-line change, so I hope it's alright I didn't raise an issue on it. Fixes what looks like a one-line error introduced in https://github.com/astral-sh/ruff-vscode/pull/379?
=> Amend `notebook.source` actions on save recommendation

.github/workflows/release.yaml
This PR ensures that we publish VS Code extensions for the `alpine-x86` and `alpine-arm64` target platforms.
See https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions for details:
> The currently available platforms are: win32-x64, win32-arm64, linux-x64, linux-arm64, linux-armhf, alpine-x64, alpine-arm64, darwin-x64, darwin-arm64 and web.
Performed a dry run, and verified that Ruff selected the correct musl wheel for x86:
And again for arm:
=> Include Alpine in target platforms

README.md, package.json, pyproject.toml, requirements-dev.txt, requirements.txt, src/common/settings.ts
Users can now specify `"ruff.ignoreStandardLIbrary": false` to turn off the standard library detection.
Closes https://github.com/astral-sh/ruff-vscode/issues/351.
=> Allow opt-out of standard library detection

package.json
=> Remove unnecessary indentation in `ruff.ignoreStandardLibrary` in `package.json`

CHANGELOG.md, package-lock.json, package.json, pyproject.toml, requirements-dev.txt, requirements.txt
Also increases the LSP version.
=> Bump version to 2024.6.0

README.md
Update ruff version in README according to the latest one supported in 2024.10.0
Not necessary
=> Update ruff version in README.md

package.json
Reference: https://github.com/microsoft/vscode-black-formatter/blob/638976ed61283a1c2e17037182ca363683f2b3a3/package.json#L36
=> Add Formatters to VS Code extension category

README.md
hi! fixed a simple typo in the root README. `showNotification` should be `showNotifications`. i double checked this in the source elsewhere. discovered the issue when adjusting the vscode setting myself, and reading the README.
n/a
=> fix typo in README for the ruff.showNotifications setting

src/extension.ts
We don't actually need to tell the user to restart VS Code when changing this setting. I put this in as a precautionary measure but from the testing I've done there doesn't seem to be a need to restart it.
https://github.com/astral-sh/ruff-vscode/assets/19577865/f1536261-abc7-4016-89c9-c61e9c4047a6
=> Remove warning about restarting VS Code that appeared when enabling/disabling the experimental server

package.json
This change removes `"onCommand:ruff.restart"` from `"activationEvents"`, because VSCode generates it automatically from `package.json` contribution declarations.
CI
=> refactor: remove unnecessary activation event

CHANGELOG.md, package-lock.json, package.json, pyproject.toml
Bumps the version to the first Alpha pre-release, `2024.19.0-dev`. A new changelog entry has also been added.
=> Bump version to `2024.19.0-dev`

.github/workflows/ci.yaml
=> fix: usage of deprecated `Node.js 16 actions`

package.json, src/common/settings.ts
This is a follow-up to https://github.com/astral-sh/ruff/pull/10984, which implemented support for common Ruff configuration options in client settings. This PR exposes these new settings in the extension configuration.
These settings are different from other extension settings, because they don't have default values. Instead, if the user does not set them, they will be sent as `null`, and the server will use project configuration instead.
At the moment, `ruff server` does not actually resolve these settings yet - settings resolution is introduced in https://github.com/astral-sh/ruff/pull/11062, which means that you'll need to work from that branch to test this PR (and vice-versa).
See the test plan in https://github.com/astral-sh/ruff/pull/11062.
=> Introduce common Ruff configuration options to extension settings

package.json, src/common/settings.ts
The new LSP supports a configuration file, and I wanted to debug some issues with it, but found that it wasn't yet wired up to VS Code.
Added a configuration file; verified in the logging that the LSP attempted to read it.
=> Expose configuration file argument for experimental server

package.json, src/common/settings.ts
Fixes https://github.com/astral-sh/ruff-vscode/issues/425 (though only in the pre-release version, since this is a feature for the new LSP server)
This is a follow-up to https://github.com/astral-sh/ruff-vscode/pull/456.
A new setting has been introduced, `Prioritize File Configuration`, which tells the extension to prioritize settings from discovered TOML files over extension settings. Extension settings will still be used when a set field in the extension is not set in the file configuration.
Refer to https://github.com/astral-sh/ruff/pull/11086 for a test plan.
=> Support prioritizing discovered TOML settings over editor settings

src/common/server.ts, src/common/utilities.ts, src/extension.ts
Fixes #488.
We no longer override the trace level on server restarts. This means that the trace level will always be set to the value of `ruff.trace.server`.
With `ruff.trace.server` set to `"off"`, you should no longer see logs in the output marked as `[Trace - ...]`.
Before:
After:
=> Remove the server trace level override that was based on the extension log level

package.json, src/extension.ts
Introduces a command to print debug information. It should look like this in the Output window:
See https://github.com/astral-sh/ruff/pull/11831 for testing information.
=> Introduce `ruff.printDebugInformation` command

README.md, package.json, src/common/settings.ts
This PR adds a `ruff.showSyntaxErrors` config option for https://github.com/astral-sh/ruff/pull/12059.
Refer to the test plan in https://github.com/astral-sh/ruff/pull/12059.
=> Add `showSyntaxErrors` extension setting

src/common/constants.ts, src/common/server.ts
This PR does two things:
1. As `ruff.path` is an array, we need to check each entry and only proceed with the first valid path ([`ruff-lsp` reference](https://github.com/astral-sh/ruff-lsp/blob/c51c77c269c3f13be2534d118b81e1c3b9bbfaff/ruff_lsp/server.py#L1773-L1784))
2. Consider `useBundled` import strategy
fixes: #507
One valid path:
```json
{
"ruff.nativeServer": true,
"ruff.importStrategy": "useBundled",
"ruff.path": ["/Users/dhruv/work/astral/ruff/target/debug/ruff"]
}
```
Logs:
```
2024-07-02 15:43:01.550 [info] Using 'path' setting: /Users/dhruv/work/astral/ruff/target/debug/ruff
2024-07-02 15:43:01.550 [info] Server run command: /Users/dhruv/work/astral/ruff/target/debug/ruff server --preview
2024-07-02 15:43:01.550 [info] Server: Start requested.
```
Multiple valid paths:
```json …
```
=> Try all `path`, consider `useBundled` import strategy

src/common/server.ts
This PR adds back the message to suggest the user that the current Ruff binary doesn't support the native server.
This was removed from the Python script in #511.
fixes: #476 
Install an older Ruff version to test this out using `pipx install --force "ruff==0.3.3"`.
And, we've another log message which displays the Ruff version similar to `ruff-lsp`:
```
2024-07-03 16:00:03.089 [info] Using the Ruff binary: /Users/dhruv/work/astral/ruff-lsp/.venv/bin/ruff
2024-07-03 16:00:03.094 [info] Found Ruff 0.4.10 at /Users/dhruv/work/astral/ruff-lsp/.venv/bin/ruff
2024-07-03 16:00:03.095 [info] Server run command: /Users/dhruv/work/astral/ruff-lsp/.venv/bin/ruff server --preview
```
=> Better error message for unsupported Ruff version

src/extension.ts
I'm not sure why this check was removed looking back at https://github.com/astral-sh/ruff-vscode/pull/431, but this validation should be done for both native server and `ruff-lsp`. Both uses a Python script which requires Python 3.7 or later and `ruff` in general also supports 3.7 and later.
Without this change, if someone were to use Python 3.6, the extension would give the following error:
```
2024-07-05 09:26:21.378 [error] Error while trying to find the Ruff binary: Error: Command failed: /Users/dhruv/.pyenv/versions/3.6.15/bin/python /Users/dhruv/work/astral/ruff-vscode/bundled/tool/find_ruff_binary_path.py
Traceback (most recent call last):
File "/Users/dhruv/work/astral/ruff-vscode/bundled/tool/find_ruff_binary_path.py", line 33, in <module>
ruff_binary_path = …
```
=> Validate Python interpreter version for native server

package.json, src/common/server.ts, src/common/settings.ts, src/common/version.ts
Superseds #505 
This PR updates the `nativeServer` setting with new values `on | off | auto` based on the suggestion at https://github.com/astral-sh/ruff-vscode/pull/505#discussion_r1659606353.
For backwards compatibility, `on` and `off` are equivalent to `true` and `false` respectively.
- Use the native server
- Show warning for “deprecated” settings
- Use `ruff-lsp`
- Show warning for “new” settings
- If `ruff` version is < `0.5.2`
- If any of the “new” settings are set, log at info level for those settings
- Use `ruff-lsp`.
- If `ruff` version is ≥ `0.5.2`
- If any of the “deprecated” settings are set, log at info level for those settings
- Use `ruff-lsp`
- Otherwise, use `ruff server`
<details><summary><b>Settings reference:</b></summary>
Here, the scope represents the following:
* …
=> Support `auto` enablement of Ruff server

src/common/server.ts, src/common/status.ts
This PR updates the status item to show the chosen server in the status bar. The value would be either `Ruff (native)` or `Ruff (ruff-lsp)`.
When `nativeServer` is `true`:
When `nativeServer` is `false`:
=> Show server kind in the status bar

package.json, src/common/server.ts, src/common/settings.ts, src/common/vscodeapi.ts, src/extension.ts
This PR adds support for [untrusted workspaces](https://code.visualstudio.com/docs/editor/workspace-trust).
This wasn't possible with `ruff-lsp` because it always required a Python interpreter to run but we can support it with the native server.
resolves: #510
Restricted configuration view:
Switching from an untrusted workspace to a trusted one:
Config:
```json
{
"ruff.nativeServer": "auto",
"ruff.path": ["/Users/dhruv/work/astral/ruff/target/debug/ruff"]
}
```
Here, the `ruff.path` configuration isn't considered. But, as soon as we trust the workspace, the server is restarted using the `ruff.path` setting as seen in the logs.
https://github.com/astral-sh/ruff-vscode/assets/67177269/954f8b65-2ae1-4424-ac89-fdf0d40f4fd9
Explicitly using native server:
```json
{
"ruff.nativeServer": "on"
} …
```
=> Add support for untrusted workspace

.github/workflows/ci.yaml, .gitignore, .prettierignore, .vscode-test.js, .vscodeignore, justfile, package.json, src/common/log/logging.ts, src/test/e2e.test.ts, src/test/helper.ts, tsconfig.json
This PR adds the TypeScript tests to the CI aka E2E tests for Linux operating system. I tried to add it for Windows but those were failing for reasons not known to me.
`npm run tests`
=> Add TypeScript tests to CI

src/extension.ts, src/testFixture/.vscode/settings.json
Fix the CI failure on `main`. I think the tests are currently unpredictable in the sense that the tests could begin _before_ the server starts which then creates the failure. The main reason I believe this is happening is because the extension uses a PubSub mechanism here:
https://github.com/astral-sh/ruff-vscode/blob/80d1b13a80ac99afb96a34ae6358d893158a65b8/src/common/python.ts#L250-L259
This change is so that it never hits this by always testing with the bundled executable and always using the native server.
I don't really have a good way to test this until it's being triggered multiple times which will verify the consistency now.
=> Avoid querying the Python extension for the interpreter

package.json, src/common/settings.ts, src/common/utilities.ts
This PR adds `ruff.logLevel` and `ruff.logFile` settings to the VS Code extension which corresponds to the same for the `ruff server`. Without these, there's no way to configure the log level and the destination for the log messages unlike other editors.
Using the following config:
```json
{
"ruff.logLevel": "debug",
"ruff.logFile": "~/playground/ruff/server.logs",
"ruff.trace.server": "messages"
}
```
I confirmed that it outputs the logs messages at the specified location.
=> Add `logLevel` and `logFile` extension setting

README.md, package.json, src/common/version.ts
This PR updates the README to reflect the stabilized `ruff server`. It also changes the minimum required version for the usage of `ruff server` in `nativeServer: auto` to be `0.5.3`.
For the README, the settings that are just a _pass through_ to the native server are removed and instead we point the users to the online settings reference. Now, the settings table only contains the ones which are specific to VS Code extension.
For review, here's the rendered README: https://github.com/astral-sh/ruff-vscode/blob/dhruv/readme/README.md
resolves: #520
=> Update to reflect the stabilized `ruff server`

README.md
This PR adds a section in the README to provide documentation around untrusted workspace support.
This is a follow-up from #523.
=> Add README section for untrusted workspace support

README.md, package.json
This PR adds a new "Troubleshooting" section to the README to help the users to find more information that the extension and the language server provides.
It also adds a new `Ruff: Show logs` command which opens the Ruff output channel.
=> Add troubleshooting section

src/common/constants.ts, src/common/server.ts
This PR updates the logic to avoid passing the `--preview` flag to the `ruff server` command when the Ruff version contains the stabilized server. 
I build the latest `main` from https://github.com/astral-sh/ruff which now removes the requirement of `--preview` flag and updated the `NATIVE_SERVER_STABLE_VERSION` flag in the extension to use `0.5.2` instead.
I checked the log messages to see when it's passing the `--preview` flag.
=> Avoid passing `--preview` flag for stable `ruff server`

README.md
This is a follow-up to https://github.com/astral-sh/ruff/pull/12380 and removes the settings table from the README and instead just keeps the link to the online docs.
=> Remove settings table, link to online docs

src/common/server.ts
If the interpreter path contains a space, then the find script fails. We need to escape the arguments that we pass to `exec`. But, it seems easier to just use `spawn`, which doesn't require escaping.
Closes https://github.com/astral-sh/ruff/issues/12394.
Created a virtual environment `foo bar` in a repo; verified that the script failed before but succeeds after this change.
=> Use `spawn` rather than `exec` to support paths with spaces

package.json, pyproject.toml
Bugfix release for https://github.com/astral-sh/ruff-vscode/pull/539
There are no changes to ruff or ruff-lsp
=> Bump version to 2024.34.0

src/common/server.ts
=> Use `execFile` rather than `spawn`

package.json
Hi, this PR fixes a typo in the `markdownDescription` of the `ruff.configurationPreference` setting.
`froml` -> `from`
N/A
=> Fix typo in ruff.configurationPreference markdownDescription

README.md
This PR adds a new section in the README to guide users to opt-in for Jupyter Notebook support for the native server. This is required because, unlike `ruff-lsp`, the native server looks at the `include` / `extend-include` setting.
Refer #546
=> Guide to opt-in to Notebook support in native server

package-lock.json, package.json, src/common/python.ts
This PR removes Python extension API definitions and instead uses `@vscode/python-extension` package.
`just test && just e2e-tests`
=> Remove Python extension API definitions

package.json, src/common/python.ts, src/common/server.ts, src/common/settings.ts, src/extension.ts
This PR updates the scope of `ruff.interpreter` setting from `window` to `resource` in order to resolve the variables such as `${workspaceFolder}` if present.
In #551, what happens is that the Python extension fails to resolve the environment corresponding to that interpreter which causes the hang. The bug present in #551 was there for a very long time but it got visible because of https://github.com/astral-sh/ruff-vscode/commit/e665ec7be83b72f7586b30387cd87c8faf62b9e1. Before that commit, the extension would just move ahead and use the interpreter from the Python extension but now we explicitly stop moving ahead if it fails to resolve the environment corresponding to the interpreter.
For reference, the `vscode-black-formatter` extension also updated the scope of `ruff.interpreter` to be …
=> Use `ruff.interpreter` from workspace settings

src/common/server.ts, src/common/settings.ts
This PR updates the `resolveVariables` to consider environment variables.
Reference: https://github.com/microsoft/vscode-black-formatter/blob/458ed8f03f03c6e021361b7dcf4a8c7ab7c3d5fb/src/common/settings.ts#L64-L71
fixes: #448 
Note that you'll need to launch the VS Code from the shell so that the VS Code process can see the variables which are present in an activate virtual environment.
```console
$ echo $VIRTUAL_ENV
/Users/dhruv/playground/ruff/.venv
$ code --extensionDevelopmentPath=/Users/dhruv/work/astral/ruff-vscode .
```
Using the following settings:
```json
{
"ruff.interpreter": ["${env:VIRTUAL_ENV}/bin/python"]
}
```
Logs:
```
2024-07-24 09:15:11.563 [info] Using interpreter: /Users/dhruv/playground/ruff/.venv/bin/python
2024-07-24 09:15:11.634 [info] Using the Ruff binary: …
```
=> Substitute environment variables in extension settings

src/common/server.ts, src/extension.ts
This PR fixes a bug to avoid awaiting the VS Code popup notifications.
For posterity, this is how to reproduce this bug:
1. Keep the extension setting to only contain:
```json
{
"ruff.nativeServer": true
}
```
2. Add the following additional setting which is incompatible with the native server:
```json
{
"ruff.nativeServer": true,
"ruff.format.args": ["--line-length=10"]
}
```
3. Saving the new settings will trigger a restart and a notification will popup which warns you about this incompatible setting (**Do NOT dismiss the notification window**)
4. Remove the `ruff.format.args` and save the settings which should then trigger a restart again
But, the restart triggered by (3) never completed because the notification was awaited and the user never dismissed it. This is where the extension …
=> Avoid awaiting VS Code popup notifications

src/extension.ts
This PR is a refactor to use `try .. finally` in the logic which starts the server to always reset the debounce state variable (`restartInProgress`). This is to ensure that it's always reset even in case of a failure.
Refer to the test plan in https://github.com/astral-sh/ruff-vscode/pull/559.
=> Use `try ... finally` to always reset debounce state

src/common/server.ts, src/extension.ts
Follow-up to #558
This PR separates the server start and stop logic.
This is required because the extension could skip starting the server in the following cases:
1. No Python interpreter is selected
2. Python extension is unable to resolve the environment for the given Python interpreter
3. Python version is incompatible
So, if the extension was already running and the settings were updated to hit any one of the above cases, the server would still be running (not ideal).
Here, the diagnostics should disappear because the server stopped first before checking for the interpreter.
For (1),
I'd need to uninstall all Python versions for me to reproduce this so I'm skipping this scenario assuming that (2) and (3) is sufficient.
For (2), …
=> Separate server start / stop logic

src/common/server.ts
This PR provides minimal support for the `red_knot` binary to run the server without performing any version checks.
I've been using this branch for my testing of https://github.com/astral-sh/ruff/pull/12624
=> Support `red_knot` binary for server

src/common/server.ts, src/test/helper.ts, src/test/utils.test.ts
I use ruff for our embedded python interpreter. This interpreter needs to be bootstrapped (env-vars) before be able to get called (technical limit of the environment itself).
This is usually done with `.cmd` file (the modern version of `.bat`) on windows which is kind of similar to `.sh` on linux.
`.cmd`  files are often use on Windows, even vscode itself use it to start vscode on windows.
Today I noticed that I get a crash when using the `.cmd` interpreter path.
It seems that node require shell mode (in windows calling `cmd.exe` as the shell) to be able to call `.cmd` files correctly.
I needed to quote the input filename as well to avoid whitespace issues which looks like a bug in node itself.
With that PR I got no crashes anymore when the extension try to run ruff 😄 .
Note: The shell …
=> Add support for Windows `.cmd` and `.bat` files

README.md
Closes  #590
- the version of Ruff, the extension is shipped with, is corrected
- info on Jupyter Notebook Support in native server is updated
didn't run any tests, as only the  README.md is changed.
=> Update README section for notebook support for Ruff 0.6

package.json
These two settings are only used from the global scope but can be defined at the workspace level. This PR updates the schema so that it's only visible in the "User" settings and not in the "Workspace" settings.
As seen in Ruff server implementation:
https://github.com/astral-sh/ruff/blob/a99832088a31b65f79e578e3131756cfdc0afb0d/crates/ruff_server/src/server.rs#L87-L95
And, we also don't have support for configuring the tracing setup for individual workspaces so it doesn't make sense either.
From https://code.visualstudio.com/api/references/contribution-points#contributes.configuration:
* `application` - Settings that apply to all instances of VS Code and can only be configured in user settings.
* `window` - Windows (instance) specific settings which can be configured in user, workspace, …
=> Use "application" scope for global only settings

src/common/server.ts
This PR includes a "Show Logs" button for all window messages from Ruff. This might be useful to reduce the friction for the users in figuring out where the logs are. This is something I saw when looking at https://github.com/koxudaxi/ruff-pycharm-plugin/issues/463 description.
=> Always include "Show Logs" button for window messages

src/common/server.ts
Ensures that the extension calls `updateStatus` with `busy=false` when the server startup is complete. 
This is now necessary after https://github.com/astral-sh/ruff-vscode/pull/600 correctly added an `updateStatus` call with `busy=true` before the server starts.
Fixes https://github.com/astral-sh/ruff-vscode/issues/605
I ran the extension and verified that the busy indicator no longer spins forever.
=> Set status to 'not-busy' when server startup is complete

.github/workflows/release.yaml
Publishing the extension to the OpenVSX registry fails a lot of times and there's no way to re-run just the publish step for the OpenVSX in GitHub Actions, we can only re-run the entire workflow. This PR separates the publish step into two where (1) would publish to Code Marketplace and (2) would publish to OpenVSX registry. This means that if we fail to publish to one of the registry, we could still re-run it.
Sometimes it does happen that only some of the artifacts are published and not all of them in which case re-running won't solve this issue. I don't really have a good solution here.
=> Separate publish steps for Code Marketplace and OpenVSX

package-lock.json, package.json
The recent version of `ovsx` had a breaking change which bumps the minimum Node version required to be 20. This broke our release workflow: https://github.com/astral-sh/ruff-vscode/actions/runs/11392480125/job/31698800337.
Similar to how we've pinned the `@vscode/vsce` which is a VS Code extension manager and is used to publish the artifacts to the VS Code Marketplace, we'll pin the `ovsx` as a dev dependency. Both had a breaking change but as the latter wasn't pinned, it used the latest version in CI.
Currently, the `ovsx` is pinned to `0.9.4` as `0.9.5` had the breaking change: https://github.com/eclipse/openvsx/blob/master/cli/CHANGELOG.md#v095-sep-2024
`npx ovsx --version` should give `0.9.4`
<details><summary>Details</summary>
<p>
```console
❯ just clean
rm -rf out
rm -rf …
```
=> Pin `ovsx` as a dev dependency

CONTRIBUTING.md
=> CONTRIBUTING: `uv` is now used to generate our `requirements.txt` files

scripts/release.py
We use a form of CalVer, so this makes more sense
=> release script: default the major version to the current year, not the existing major version

src/common/server.ts, src/extension.ts
I noticed this in https://github.com/astral-sh/ruff-vscode/pull/585 that we would not be able to look at the error message when the server crashes because the output window got disposed. This is because the disposable is tied up with stopping the server. This PR updates that to include the disposable to the extension context so that it gets disposed only when the extension is deactivated.
Run the scenario from https://github.com/astral-sh/ruff-vscode/pull/585 to make sure that the "Ruff Language Server" window is not disposed in case the server crashed.
=> Use extension context for output window disposable

src/common/server.ts, src/extension.ts
These channels should only be created once during the activation of the extension. Otherwise, restarting the extension hangs.
=> fixup! Use extension context for output window disposable (#671)

README.md, package.json, src/common/server.ts
This PR adds the deprecation message to `ruff-lsp` specific settings and update the README section with a [warning message](https://github.com/astral-sh/ruff-vscode/blob/dhruv/deprecate/README.md#python-based-language-server-ruff-lsp).
There doesn't seem to be any way to show this to the user as the settings are now not visible in the settings UI although they're visible in the JSON viewer:
But, it's not visible in the hover window of the settings:
Additionally, the extension will provide a deprecation warning when Ruff version if < 0.3.5. For >= 0.3.5, `ruff-lsp` will provide the warning (https://github.com/astral-sh/ruff-lsp/pull/520).
Preview of this warning:
=> Add deprecation warning for `ruff-lsp` specific settings

package.json
Based on feedback in https://github.com/astral-sh/ruff/discussions/15991#discussioncomment-12095853, https://github.com/astral-sh/ruff/discussions/15991#discussioncomment-12099643.
=> Undeprecate `ruff.nativeServer`

src/common/server.ts, src/common/settings.ts
This PR is inspired by [this feedback](https://github.com/astral-sh/ruff/discussions/15991#discussioncomment-12144115) and adds the location of the legacy settings explicitly set by the user in the deprecation message. We already have that information so let's surface it to the user.
User settings:
```json
{
"ruff.nativeServer": "on",
"ruff.lint.args": []
}
```
Workspace folder settings (`${workspaceFolder}/.vscode/settings.json`):
```json
{
"ruff.ignoreStandardLibrary": "true"
}
```
=> Include legacy server setting location in deprecation message

src/common/commands.ts, src/extension.ts
This PR does a small refactor to move the commands implementation into a separate `commands.ts` to reduce the complexity in `extension.ts`.
=> Move command implementation to `commands.ts`

src/common/settings.ts, src/extension.ts
This PR adds a check for `notebook.codeActionsOnSave` to do the following:
* For `source.fixAll` and `source.organizeImports`, log at info level
* For `source.fixAll.ruff` and `source.organizeImports.ruff`, log at warn level and provide a warning message to use `notebook.` prefixed code actions instead
Using the following settings:
```json
{
"notebook.codeActionsOnSave": {
"source.fixAll": "explicit",
"source.organizeImports": "explicit",
"source.organizeImports.ruff": "explicit",
"source.fixAll.ruff": "explicit"
}
}
```
Logs:
```
2025-02-17 20:06:34.796 [info] The following code actions in 'notebook.codeActionsOnSave' could lead to unexpected behavior: ["source.fixAll","source.organizeImports"]. Consider using ["notebook.source.fixAll","notebook.source.organizeImports"] instead. For more …
```
=> Warn against certain values in `notebook.codeActionsOnSave`

src/common/server.ts
The extension now also recognizes `red_knot.exe` as a Red Knot affix.
None.
=> Make it easier for Windows users to test Red Knot

package.json, src/common/server.ts, src/common/settings.ts, src/common/version.ts
Closes: #6 
This PR adds support for https://github.com/astral-sh/ruff/pull/16296 for the VS Code extension by allowing any arbitrary object in `ruff.configuration`
Additionally, it will provide a warning message to the user if they're using inline configuration but the Ruff version does not support it.
It has one disadvantage that the user will see two popups where the error one is coming from the server because it cannot deserialize the options. We could not show the warning popup if this is too much. I'm worried that it might go unnoticed because the "Show Logs" in the below popup will open the server logs while the message would be in the client logs.
We'll still log it on the console (client log channel):
```
2025-02-25 13:24:10.067 [warning] Inline configuration support was added in …
```
=> Allow arbitrary config keys in `ruff.configuration`

src/common/settings.ts
fixup from #702 
Verified that `null` (not setting `ruff.configuration`) doesn't give me the warning.
=> Avoid inline config warning when value is `null`

src/common/server.ts
In response to the feedback given at https://github.com/astral-sh/ruff/discussions/15991#discussioncomment-12423803.
=> Improve deprecation message for old Ruff version

.github/workflows/release.yaml
I noticed the warnings about the Ubuntu 20.04 brownout during the release today. We're actually only 10 days from the end of the brownout period and when 20.04 is fully unsupported ([ref](https://github.com/actions/runner-images/issues/11101)).
There's one additional mention of 20.04 a bit farther down in the file for the `run-on-arch` action, but that's the same with Ruff.
Possibly we could also bump all the way to 24.04 if we wanted.
=> Bump Ubuntu version in release workflow

src/common/server.ts
This PR adds both workspace and global client settings at INFO level.
Maybe this would be more useful at the server level but this could also reveal some bug on the client side code.
```
2025-04-29 16:06:02.475 [info] Using interpreter: /Users/dhruv/work/astral/ruff-vscode/.venv/bin/python
2025-04-29 16:06:02.477 [info] Workspace settings for /Users/dhruv/playground/ruff: {
"nativeServer": "on",
"cwd": "/Users/dhruv/playground/ruff",
"workspace": "file:///Users/dhruv/playground/ruff",
"path": [
"/Users/dhruv/work/astral/ruff/target/debug/ruff"
],
"ignoreStandardLibrary": true,
"interpreter": [
"/Users/dhruv/work/astral/ruff-vscode/.venv/bin/python"
],
"configuration": "/Users/dhruv/playground/ruff/formatter/ruff.toml",
"importStrategy": "fromEnvironment",
"codeAction": {
"fixViolation": { …
```
=> Log client settings for workspace and global

pyproject.toml
This never gets built as a package; this is just used for metadata.
=> Remove unnecessary metadata from `pyproject.toml`

.github/workflows/ci.yaml
Use setup-uv 
We still need setup-python because PBS doesn't support Python 3.7
=> fix CI failure on main

pyproject.toml
This reverts a small part of #750. The `version` field is used by the release script, so I think we should keep it around.
I added back `2025.22.0` before running the release script, which was then updated to `2025.24.0`. That's why this is stacked on the release branch too.
=> Restore version field in `pyproject.toml`
