- bundled/tool/_debug_server.py
- bundled/tool/jsonrpc.py
- bundled/tool/runner.py
- bundled/tool/server.py
- bundled/tool/utils.py
- package-lock.json
- package.json
- pyproject.toml
- src/test/python_tests/lsp_test_client/constants.py
- src/test/python_tests/lsp_test_client/defaults.py
- src/test/python_tests/lsp_test_client/session.py
- src/test/python_tests/lsp_test_client/utils.py
- src/test/python_tests/test_server.py
> Use absolute path to bundled binary

- .github/workflows/release.yaml
- .vscodeignore
- noxfile.py
- package-lock.json
- package.json
> Automate multi-platform builds and publishing to Code Marketplace

- .vscodeignore
> Add .idea and .ruff_cache to .vscodeignore

- bundled/tool/server.py
> Use scripts path when interpreter is set

- .github/workflows/release.yaml
- package-lock.json
- package.json
Mostly taken from [rust-analyzer](https://github.com/rust-lang/rust-analyzer/blob/d2281f0367ba85c34ee9bce07d3cca40e1424721/editors/code/package.json#L52).
Closes #29.
> Publish to OpenVSX

- .github/workflows/ci.yaml
- bundled/tool/server.py
> Delay import of typing_extensions

- README.md
> Add docs on replacing Black et al

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- LICENSE
- README.md
- build/generate_build_id.py
- build/update_ext_version.py
- noxfile.py
- package.json
- pyproject.toml
> Enable nightly pre-release builds

- .vscodeignore
> Exclude build-only artefacts from vsix

- .eslintrc.json
- src/extension.ts
> Fix eqeqeq warning

- package-lock.json
- package.json
I'm not sure what these were testing, but even from the first commit, the files they try to execute don't exist.
> Remove unused test commands

- package.json
See: https://github.com/microsoft/vscode-python/issues/21459.
> Mark virtual workspaces as unsupported in package.json

- src/extension.ts
Updated the link for the issue tracker after the astral-sh move
n/a
> Update issue tracker link to astral-sh

- README.md
Duplicate of https://github.com/astral-sh/ruff-lsp/pull/273
> Add fix safety notes to readme

- README.md
Closes https://github.com/astral-sh/ruff-vscode/issues/318.
> Add note on isort enablement

- package.json
Closes https://github.com/astral-sh/ruff-vscode/issues/331.
> Change `showNotifications` to a window setting

- README.md
- package.json
We should probably wait until `ruff-lsp` is released before we merge this PR.
> Update with Notebook support

- CHANGELOG.md
- package-lock.json
- package.json
- pyproject.toml
- requirements-dev.txt
- requirements.txt
> Bump version to 2023.48.0

- package-lock.json
- package.json
- pyproject.toml
> Bump version to 2023.55.0-dev

- src/common/settings.ts
Ensures that the VS Code-specific environment variables, like `${userHome}`, are resolved when reading the configuration file path.
Added `"ruff.configuration": "${userHome}/x.toml"` to `settings.json`; verified via logs that the extension `Failed to read /Users/crmarsh/x.toml`.
> Expand VS Code variables when resolving configuration argument

- .github/workflows/ci.yaml
- src/extension.ts
I'm disabling this for now until I'm able to reproduce the failure.
> Disable TypeScript CI

- README.md
Direct to the right section within docs/faq
No tests
> fix(url): match right url to direct to `change default config` section

- src/extension.ts
Related to https://github.com/astral-sh/ruff/pull/16215
The output in https://github.com/astral-sh/ruff/pull/16215 is by using this PR.
> Pass active document URI for debug command

- scripts/release.py
This PR adds some assertions to the release script that makes sure that:
- There is exactly one match of the description regex in the README
- There is at least one match of the svg regex in the README
This makes the script more robust to unexpected changes in Ruff's versioning scheme or the prose in the README.
- I ran the script on this branch as-is and it ran successfully without updating the README (because there's currently nothing to update)
- I ran `git checkout 5ea1add14470e3bb15b8bfd3580c5fddeb3d117f -- README.md CHANGELOG.md package.json package-lock.json pyproject.toml requirements.txt requirements-dev.txt` to revert all changes from the last release. I then re-ran the release script. The diff relative to this branch was:
```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index …
```
> Add some more assertions to regexes in the release script
